### PR TITLE
Added ACM-W Scholarship

### PR DESCRIPTION
**Pull request by CheshtaK**

### CODE REVIEW

**Comment by XinYi-Karen-Zheng** [comment]
Where exactly did you find the application for this scholarship? When I go to the linked you provided for ACM-W and follow the link after "For scholarships to attend the Grace Hopper Celebration of Women in computing apply here", it just redirects to https://ghc.anitab.org/ and I cannot figure out where the scholarship is.

**Comment by CheshtaK** [comment]
Hey! If you scroll down the page you'll see an option which will direct you to the application form. You're supposed to set up an account in order to apply for the scholarship.

Screenshot (12)_LI

**Comment by XinYi-Karen-Zheng** [comment]
@CheshtaK Oh I see. Thank you!

**Comment by aceyoung9** [comment]
Manually merged @ 259b4ec

Thank you!

**Pull request closed without merging**
