### PR TITLE
Add Google GHC scholarship details and fix some spelling

### PR DESCRIPTION
**Pull request by mahdouglass**

### CODE REVIEW

**Comment by diksha11s** [comment]
Please provide the link for Google GHC scholarship.

**Comment by mahdouglass** [comment]
Here is the link: https://docs.google.com/forms/d/e/1FAIpQLScSjfft02VOvX7npmwCgdCzclpgSlS6s8HHOdlptyFau4YlmQ/viewform Is the link included in my PR not working?

**Comment by blossomica** [comment]
@mahdouglass  - It is working :+1:

**Comment by aceyoung9** [comment]
Thanks @mahdouglass @diksha11s @blossomica !

**Pull request merged**
