### PR TITLE
Facebook changed their decision date to July 29th

### PR DESCRIPTION
**Pull request by lisageeee**

### CODE REVIEW

**Comment by blossomica** [comment]
@lisageeee - Where does it note the change in the decision date? Their website currently still has the old date.

**Comment by lisageeee** [comment]
@blossomica I received an email from them saying:

 "Thank you for your application to the Grace Hopper Celebration Scholarship with Facebook. We are writing to update you that selection decisions have not yet been released. Due to a larger number of applications than expected, our selection and review processes are taking longer than anticipated.
 
Our new expected timeline for decisions is by July 29th at the latest. We will notify all applicants of their application status by that date."

**Comment by blossomica** [comment]
@lisageeee  - Thanks for the confirmation. I haven't received that email. It seems some other people have as well not received that notification so I'd try to investigate it.

**Comment by kim-codes** [comment]
I got this e-mail as well. 

screen shot 2017-07-17 at 10 54 38 am

**Comment by blossomica** [comment]
@kim-codes  - Thanks for the confirmation too, I sent an email to them and I got a reply that they will check their mailing list and try to send the message across so indeed the date has shifted. Hopefully, soon the new date will be updated on their website and communicated further.

**Comment by aceyoung9** [comment]
Thanks, everyone! Merging.

**Pull request merged**
