### PR TITLE
combine 2017 tables

### PR DESCRIPTION
**Pull request by madsesmith**

### CODE REVIEW

**Comment by aceyoung9** [comment]
https://github.com/Ladies-Storm-Hackathons/GHC-Scholarships/pull/30/files -- wait, didn't you submit a change a few weeks ago, with the tables separated?

Can I also ask why you'd like the scholarships that are no longer open for submissions to be in the same table as the scholarships that are still open? Once more scholarships are listed, it seems like having two separate tables will make it easier for users to skim.

thoughts?

**Comment by madsesmith** [comment]
@aliceyoung9 looks like you're right. I actually intended for it to be one combined table then but clearly messed up. (The Microsoft scholarship was still open when I submitted the pull request, so there wouldn't have been any logic to two separate tables). oops!

I could imagine people wanting separate ones that are open/closed like you suggested. But it might be best to keep them in one table so the columns remain lined up* so people can easily scan to compare across all the 2017 scholarships (such as to see which results have been released). What if we did one column with an empty row separating the open and closed scholarships?

*markdown will auto-adjust the column widths depending on the contents so the columns of the two tables won't line up even if their headers are exactly the same.

**Comment by aceyoung9** [comment]
Ok; I like the empty row idea. Wanna send in a patch with that?

**Comment by aceyoung9** [comment]
Merged! Sorry for taking 5ever; thanks for contributing!

**Pull request merged**
